#include "../include/transmission_timings.h"

const uint32_t T_START_SIZE = 10;
const elem_timing t_start[] = {
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 144 },
};

const uint32_t T_BODY_SIZE = 65;
const elem_timing t_body[] = {
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 144 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 144 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 144 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 144 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 144 },
	{ .on = false, .duration = 336 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 144 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 144 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 144 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 144 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 144 },
};

const uint32_t T_LOOP_SIZE = 10;
const elem_timing t_loop[] = {
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 144 },
};

const uint32_t T_FIN_SIZE = 12;
const elem_timing t_fin[] = {
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 48 },
	{ .on = false, .duration = 48 },
	{ .on = true, .duration = 144 },
	{ .on = false, .duration = 144 },
};

